const CERT_CATEGORIES = [
  {
    slug: 'recent',
    name: 'Most Recent',
    items: [
      { src: 'certificates/2026/ghl-training.png', label: 'Go High Level Training Course (VAA Pro, 2026)' },
      { src: 'certificates/2026/ecom.png', label: 'E-Commerce Virtual Assistant Training (VAA Pro, 2026)' },
      { src: 'certificates/Udemy/udemy-AI.jpg', label: 'Udemy — AI Certificate' },
    ]
  },
  {
    slug: 'professional',
    name: 'Professional Certificates & Digital Badges',
    items: [
      { src: 'certificates/full-stack.png', label: 'Full-Stack Development' },
      { src: 'certificates/ibm-front-end.JPG', label: 'IBM Front-End Development' },
      { src: 'certificates/professional-meta.jpeg', label: 'Meta Professional Certificate' },
      { src: 'certificates/Coursera/back-end-professional.jpg', label: 'Back-End Professional Certificate' },
      { src: 'certificates/Coursera/social-pro.jpg', label: 'Social Media Professional Certificate' },
      { src: 'certificates/google-pro.jpg', label: 'Google Professional Certificate' },
      { src: 'images/badges/image.png', label: 'Meta — Front-End Developer (Digital Badge)' },
      { src: 'images/badges/badge2.png', label: 'IBM — Web Development with HTML, CSS, JavaScript (Digital Badge)' },
      { src: 'images/badges/badge3.png', label: 'IBM — Front-End Development with React (Digital Badge)' },
      { src: 'images/badges/badge4.png', label: 'IBM — Introduction to Cybersecurity Tools & Cyber Attacks (Digital Badge)' },
    ]
  },
  {
    slug: 'cyber',
    name: 'Cybersecurity',
    items: [
      { src: 'certificates/Coursera/cyber1.jpg' },
      { src: 'certificates/ethical-hacking.png', label: 'Ethical Hacking' },
      { src: 'certificates/Coursera/cyber-2.jpg' },
      { src: 'certificates/Coursera/ibm-cyber1.jpg', label: 'IBM Cybersecurity' },
      { src: 'certificates/Coursera/cyber3.jpg' },
      { src: 'certificates/Coursera/cyber5.jpg' },
      { src: 'certificates/Coursera/cyber4.jpg' },
    ]
  },
  {
    slug: 'ecommerce',
    name: 'E-Commerce & Marketing',
    items: [
      { src: 'certificates/2026/ghl-training.png', label: 'Go High Level Training Course (VAA Pro, 2026)' },
      { src: 'certificates/google-1.jpg' },
      { src: 'certificates/google-2.jpg' },
      { src: 'certificates/google-3.jpg' },
      { src: 'certificates/google-4.jpg' },
      { src: 'certificates/google-5.jpg' },
      { src: 'certificates/google-6.jpg' },
      { src: 'certificates/google-7.jpg' },
      { src: 'certificates/kurso/coffee.png' },
      { src: 'certificates/kurso/fbads.jpg', label: 'Facebook Ads' },
      { src: 'certificates/kurso/graphic.png', label: 'Graphic Design' },
      { src: 'certificates/kurso/socialmedia.jpg', label: 'Social Media Marketing' },
      { src: 'certificates/kurso/wordpress.png', label: 'WordPress' },
    ]
  },
  {
    slug: 'social',
    name: 'Social Media Marketing',
    items: [
      { src: 'certificates/Social-Media/1.jpg' },
      { src: 'certificates/Coursera/social2.jpg' },
      { src: 'certificates/Coursera/social3.jpg' },
      { src: 'certificates/Coursera/social4.jpg' },
      { src: 'certificates/Coursera/social5.jpg' },
      { src: 'certificates/Coursera/social6.jpg' },
    ]
  },
  {
    slug: 'webdev',
    name: 'Web Development',
    items: [
      { src: 'certificates/Udemy/udemy1.jpg' },
      { src: 'certificates/Udemy/udemy2.jpg' },
      { src: 'certificates/Coursera/IBM/intro-to-se.jpg', label: 'IBM — Intro to Software Engineering' },
      { src: 'certificates/ibm-capstone.JPG', label: 'IBM Capstone' },
      { src: 'certificates/ibm-uiux.JPG', label: 'IBM UI/UX' },
      { src: 'certificates/IBM-introduction.jpg', label: 'IBM Introduction' },
      { src: 'certificates/IBM-react1.jpg', label: 'IBM React' },
      { src: 'certificates/Coursera/CERTIFICATE_LANDING_PAGE_UNUTUYPXG33D.jpeg', label: 'IBM — Developing Front-End Apps with React' },
      { src: 'certificates/Coursera/IBM/IBM-cloud.png', label: 'IBM Cloud' },
      { src: 'certificates/Coursera/IBM/git-github.jpg', label: 'Git & GitHub' },
      { src: 'certificates/meta-front-end.jpeg', label: 'Meta — Front-End Developer' },
      { src: 'certificates/Coursera/front-end-meta.jpeg', label: 'Meta — Front-End Developer' },
      { src: 'certificates/meta-advanced-react.jpeg', label: 'Meta — Advanced React' },
      { src: 'certificates/Coursera/advanced-react.jpeg', label: 'Meta — Advanced React' },
      { src: 'certificates/meta-react-basics.jpg', label: 'Meta — React Basics' },
      { src: 'certificates/Coursera/react-basics.jpeg', label: 'Meta — React Basics' },
      { src: 'certificates/meta-programming-with-javascript.jpg', label: 'Meta — Programming with JavaScript' },
      { src: 'certificates/Coursera/programming-with-javascript.jpeg', label: 'Meta — Programming with JavaScript' },
      { src: 'certificates/meta-html-in-depth.jpg', label: 'Meta — HTML & CSS in Depth' },
      { src: 'certificates/Coursera/html-css-in-depth.jpeg', label: 'Meta — HTML & CSS in Depth' },
      { src: 'certificates/meta-ui-ux.jpg', label: 'Meta — UI/UX Design' },
      { src: 'certificates/Coursera/UI-UX.jpeg', label: 'Meta — UI/UX Design' },
      { src: 'certificates/meta-version-control.jpg', label: 'Meta — Version Control' },
      { src: 'certificates/Coursera/version-control.jpeg', label: 'Meta — Version Control' },
      { src: 'certificates/meta-intro-to-frontend.jpg', label: 'Meta — Intro to Front-End Development' },
      { src: 'certificates/Coursera/introduction-to-front-end.jpeg', label: 'Meta — Intro to Front-End Development' },
      { src: 'certificates/meta-intro-to-backend.jpg', label: 'Meta — Intro to Back-End Development' },
      { src: 'certificates/Coursera/introduction-to-back-end.jpeg', label: 'Meta — Intro to Back-End Development' },
      { src: 'certificates/backend222.jpeg', label: 'Back-End Development' },
      { src: 'certificates/Coursera/python.jpg', label: 'Python' },
      { src: 'certificates/database.jpg', label: 'Database' },
      { src: 'certificates/Coursera/back-end-capstone.jpg', label: 'Back-End Capstone' },
      { src: 'certificates/Coursera/API.jpg', label: 'APIs' },
      { src: 'certificates/Coursera/django.jpg', label: 'Django' },
      { src: 'certificates/Coursera/thefullstack.jpg', label: 'The Full Stack' },
      { src: 'certificates/Coursera/coding-interview-preparation.jpeg', label: 'Coding Interview Preparation' },
      { src: 'certificates/Codecademy/front-end-engineer.png', label: 'Codecademy — Front-End Engineer' },
      { src: 'certificates/Codecademy/back-end.png', label: 'Codecademy — Back-End' },
      { src: 'certificates/Codecademy/build-a-website.png', label: 'Codecademy — Build a Website' },
      { src: 'certificates/Codecademy/css-intermediate.png', label: 'Codecademy — CSS Intermediate' },
      { src: 'certificates/Codecademy/learn-css.png', label: 'Codecademy — Learn CSS' },
      { src: 'certificates/Codecademy/learn-css2.png', label: 'Codecademy — Learn CSS II' },
      { src: 'certificates/Codecademy/learn-html.png', label: 'Codecademy — Learn HTML' },
      { src: 'certificates/Codecademy/learn-javascript.png', label: 'Codecademy — Learn JavaScript' },
      { src: 'certificates/Codecademy/learn-jquery.png', label: 'Codecademy — Learn jQuery' },
      { src: 'certificates/Codecademy/learn-testing.png', label: 'Codecademy — Learn Testing' },
      { src: 'certificates/Codecademy/php-introduction.png', label: 'Codecademy — Intro to PHP' },
      { src: 'certificates/front-end-app.png', label: 'Front-End App' },
      { src: 'certificates/building-interactive-website.png', label: 'Building Interactive Websites' },
      { src: 'certificates/Codecademy/ui-ux.png', label: 'Codecademy — UI/UX' },
      { src: 'certificates/codeliber1.png', label: 'Codeliber' },
      { src: 'certificates/Coursera/IBM/Coursera LMPG7KTVP6HQ.pdf', pdf: true, label: 'IBM Course Certificate (PDF)' },
      { src: 'certificates/Coursera/IBM/Coursera Q34BCC2DUEJW.pdf', pdf: true, label: 'IBM Course Certificate (PDF)' },
    ]
  },
  {
    slug: 'other',
    name: 'Other Certificates',
    items: [
      { src: 'certificates/Coursera/AI.jpg', label: 'AI' },
      { src: 'certificates/others1.jpg' },
      { src: 'certificates/Coursera/mobile1.jpg', label: 'Mobile Development' },
      { src: 'certificates/kurso/tesda-cert.png', label: 'TESDA Certificate' },
      { src: 'certificates/mci.jpg' },
      { src: 'certificates/SEO.PNG', label: 'SEO' },
      { src: 'certificates/goit.png' },
    ]
  },
];
