const PROJECT_GROUPS = [
  { title: 'Shopify Store 1', images: ['shopify1.png','shopify2.png','shopify3.png','shopify4.png','shopify5.png'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 2', images: ['a1.jpg','a2.jpg','a3.jpg','a4.jpg','a5.jpg','a6.jpg'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 3', images: ['c1.jpg','c2.jpg','c32.jpg','c4.jpg','c5.jpg','c6.jpg'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 4', images: ['h1.PNG','h2.PNG','h3.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 5', images: ['i1.PNG','i2.PNG','i3.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 6 (Prime Health)', images: ['primehealth1.PNG','primehealth2.PNG','primehealth3.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 7 (Brew Can Do It)', images: ['brewcandoit1.PNG','brewcandoit2.PNG','brewcandoit3.PNG','brewcandoit4.PNG','brewcandoit5.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 8', images: ['shopifya1.png','shopifya2.png','shopifya3.png','shopifya4.png','shopifya5.png','shopifya6.png'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 9', images: ['shopifyb1.png','shopifyb2.png','shopifyb3.png','shopifyb4.png','shopifyb5.png','shopifyb6.png'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 10', images: ['b1.jpg','b2.jpg','b3.jpg','b4.jpg','b5.jpg','b6.jpg'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 11', images: ['g1.jpg','g2.jpg','g3.jpg','g4.jpg','g5.jpg','g6.jpg'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify Store 12 - Northside Music Store', images: ['northsidemusic1.PNG','northsidemusic2.PNG','northsidemusic3.PNG','northsidemusic4.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
  { title: 'Shopify 13 - www.yicaprints.site', link: 'https://www.yicaprints.site', images: ['yicaprints1.PNG','yicaprints2.PNG','yicaprints3.PNG'].map(f => ({ src: 'images/shopify/' + f })) },
];
